name: Publish Auto Docs to Github Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout auto-docs repo.
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        ref: main

    # Checkout repos we're pulling into the build.
    - name: Checkout REPO_NAME
      uses: actions/checkout@v3

    - name: Clone a public repository
      run: |
        git clone https://github.com/jomurgel/REPO_NAME.git

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version-file: './.nvmrc'

    - name: Install Node Dependencies
      working-directory: ./
      run: npm ci

    - name: Generate docs
      working-directory: ./
      run: |
        npm run docs generate

    # Cleanup REPOS before we deploy.
    - name: Remove source directory
      working-directory: ./
      run: |
        rm -rf REPO_NAME

    - name: Build Docs
      working-directory: ./
      run: npm run export

    - name: Deploy
      # https://github.com/JamesIves/github-pages-deploy-action
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: out
